eval:
  initial_environment_result: {'Oxford': 92.2}
  environments: {
    'Oxford': {
      'stage_introduced': 0,
      'database_files': ['/media/ros/SSData/dataset/Incloud_dataset/pkl_new/Oxford_evaluation_database.pickle'], #['pickles/Oxford/oxford_evaluation_database.pickle'],
      'query_files': ['/media/ros/SSData/dataset/Incloud_dataset/pkl_new/Oxford_evaluation_query.pickle'],
    },
  }
  world_thresh: {
    'Oxford': 25,
    'DCC': 10,
    'Riverside': 10,
    'In-house': 25
  }
  false_pos_thresh: {
    'Oxford': -1,
    'DCC': 20,
    'Riverside': 20,
    'In-house': -1
  }
  time_thresh: {
    'Oxford': -1,
    'DCC': 90,
    'Riverside': 90,
    'In-house': -1
  }

