eval:
  initial_environment_result: {'Oxford': 94.06}
  environments: {
    'Oxford': {
      'stage_introduced': 0,
      'database_files': ['/media/ros/SSData/dataset/Incloud_dataset/pkl_new/Oxford_evaluation_database.pickle'], #['pickles/Oxford/oxford_evaluation_database.pickle'],
      'query_files': ['/media/ros/SSData/dataset/Incloud_dataset/pkl_new/Oxford_evaluation_query.pickle'],
    },
    'DCC': {
      'stage_introduced': 1,
      'database_files': ['/media/ros/SSData/dataset/Incloud_dataset/pkl_new/DCC_02_evaluation_database.pickle', '/media/ros/SSData/dataset/Incloud_dataset/pkl_new/DCC_03_evaluation_database.pickle'],
      'query_files': [null, null],
    },
    'Riverside': {
      'stage_introduced': 2,
      'database_files': ['/media/ros/SSData/dataset/Incloud_dataset/pkl_new/Riverside_02_evaluation_database.pickle', '/media/ros/SSData/dataset/Incloud_dataset/pkl_new/Riverside_03_evaluation_database.pickle'],
      'query_files': [null, null],
    },
    'In-house': {
      'stage_introduced': 3,
      'database_files': ['/media/ros/SSData/dataset/Incloud_dataset/pkl_new/business_evaluation_database.pickle','/media/ros/SSData/dataset/Incloud_dataset/pkl_new/residential_evaluation_database.pickle','/media/ros/SSData/dataset/Incloud_dataset/pkl_new/university_evaluation_database.pickle'],
      'query_files': ['/media/ros/SSData/dataset/Incloud_dataset/pkl_new/business_evaluation_query.pickle','/media/ros/SSData/dataset/Incloud_dataset/pkl_new/residential_evaluation_query.pickle','/media/ros/SSData/dataset/Incloud_dataset/pkl_new/university_evaluation_query.pickle'],
    },
  }
  world_thresh: {
    'Oxford': 25,
    'DCC': 10,
    'Riverside': 10,
    'In-house': 25
  }
  false_pos_thresh: {
    'Oxford': -1,
    'DCC': 20,
    'Riverside': 20,
    'In-house': -1
  }
  time_thresh: {
    'Oxford': -1,
    'DCC': 90,
    'Riverside': 90,
    'In-house': -1
  }
